export const ANALYTICS_EVENTS = {
	attendanceCheckinCompleted: "attendance_checkin_completed",
	attendanceCheckinFailed: "attendance_checkin_failed",
	attendanceCheckoutCompleted: "attendance_checkout_completed",
	attendanceCheckoutFailed: "attendance_checkout_failed",
	auditLogFiltered: "audit_log_filtered",
	authRedirectFailed: "auth_redirect_failed",
	billingCheckoutFailed: "billing_checkout_failed",
	billingCheckoutRedirectOpened: "billing_checkout_redirect_opened",
	billingCheckoutStarted: "billing_checkout_started",
	billingPortalFailed: "billing_portal_failed",
	billingPortalOpened: "billing_portal_opened",
	billingToggleSwitched: "billing_toggle_switched",
	centerCreated: "center_created",
	centerSettingsUpdated: "center_settings_updated",
	centerSwitched: "center_switched",
	checkoutCompleted: "checkout_completed",
	checkoutStarted: "checkout_started",
	childCreated: "child_created",
	childReactivated: "child_reactivated",
	childUpdated: "child_updated",
	childWithdrawn: "child_withdrawn",
	classroomArchived: "classroom_archived",
	classroomChildAssigned: "classroom_child_assigned",
	classroomChildUnassigned: "classroom_child_unassigned",
	classroomCreated: "classroom_created",
	classroomRestored: "classroom_restored",
	classroomStaffAssigned: "classroom_staff_assigned",
	classroomStaffUnassigned: "classroom_staff_unassigned",
	classroomUpdated: "classroom_updated",
	costCalculatorTeamSizeChanged: "cost_calculator_team_size_changed",
	ctaClicked: "cta_clicked",
	emailFieldAbandoned: "email_field_abandoned",
	emailFieldFocused: "email_field_focused",
	engagedTimeReached: "engaged_time_reached",
	enrollmentCompleted: "enrollment_completed",
	enrollmentStarted: "enrollment_started",
	enterpriseDiscoveryClicked: "enterprise_discovery_clicked",
	exitPopupConverted: "exit_popup_converted",
	exitPopupDismissed: "exit_popup_dismissed",
	exitPopupShown: "exit_popup_shown",
	faqExpanded: "faq_expanded",
	financeActionCompleted: "finance_action_completed",
	financeActionFailed: "finance_action_failed",
	googleLoginStarted: "google_login_started",
	guardianCreated: "guardian_created",
	guardianDeleted: "guardian_deleted",
	guardianLinkUpdated: "guardian_link_updated",
	guardianLinked: "guardian_linked",
	guardianUnlinked: "guardian_unlinked",
	guardianUpdated: "guardian_updated",
	importCompleted: "import_completed",
	importFailed: "import_failed",
	leadMagnetSubmission: "lead_magnet_submission",
	listFiltered: "list_filtered",
	loginCompleted: "login_completed",
	loginStarted: "login_started",
	messageRedelivered: "message_redelivered",
	messageRepliesRead: "message_replies_read",
	messageSendCompleted: "message_send_completed",
	messageSendFailed: "message_send_failed",
	messageThreadOpened: "message_thread_opened",
	onboardingCompleted: "onboarding_completed",
	onboardingStarted: "onboarding_started",
	pageView: "$pageview",
	paymentFailed: "payment_failed",
	pricebookBuilderInputsChanged: "pricebook_builder_inputs_changed",
	pricebookPdfRequested: "pricebook_pdf_requested",
	publicSignupSubmission: "public_signup_submission",
	publicSurveySubmission: "public_survey_submission",
	quickBooksActionCompleted: "quickbooks_action_completed",
	quickBooksActionFailed: "quickbooks_action_failed",
	ratioViolationNotesUpdated: "ratio_violation_notes_updated",
	referralLinkCopied: "referral_link_copied",
	reportDownloaded: "report_downloaded",
	reportGenerated: "report_generated",
	scheduleCreated: "schedule_created",
	scheduleUpdated: "schedule_updated",
	scrollDepthReached: "scroll_depth_reached",
	sectionViewed: "section_viewed",
	shiftCreated: "shift_created",
	shiftUpdated: "shift_updated",
	signupCompleted: "signup_completed",
	signupDuplicate: "signup_duplicate",
	signupStarted: "signup_started",
	signupSubmitted: "signup_submitted",
	signupValidationFailed: "signup_validation_failed",
	stripeConnectOnboardingFailed: "stripe_connect_onboarding_failed",
	stripeConnectOnboardingStarted: "stripe_connect_onboarding_started",
	subscriptionCheckoutCompleted: "subscription_checkout_completed",
	subscriptionStarted: "subscription_started",
	subscriptionStatusChanged: "subscription_status_changed",
	surveyCompleted: "survey_completed",
	teamMemberInvited: "team_member_invited",
	teamMemberRemoved: "team_member_removed",
	trialExpired: "trial_expired",
	trialStarted: "trial_started",
} as const;

export type AnalyticsEvent = (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];

function bytesToHex(bytes: Uint8Array): string {
	return Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
}

export async function analyticsDistinctId(kind: string, id: string): Promise<string> {
	const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(`${kind}:${id}`));
	return `${kind}:${bytesToHex(new Uint8Array(digest))}`;
}
