/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayTokenRouteImport } from './routes/pay/$token'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthOverviewRouteImport } from './routes/_auth/overview'
import { Route as AuthHelpRouteImport } from './routes/_auth/help'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthAttendanceRouteImport } from './routes/_auth/attendance'
import { Route as AuthAccountRouteImport } from './routes/_auth/account'
import { Route as AuthSubsidiesIndexRouteImport } from './routes/_auth/subsidies/index'
import { Route as AuthSchedulingIndexRouteImport } from './routes/_auth/scheduling/index'
import { Route as AuthReportsIndexRouteImport } from './routes/_auth/reports/index'
import { Route as AuthRatiosIndexRouteImport } from './routes/_auth/ratios/index'
import { Route as AuthMessagesIndexRouteImport } from './routes/_auth/messages/index'
import { Route as AuthImportIndexRouteImport } from './routes/_auth/import/index'
import { Route as AuthGuardiansIndexRouteImport } from './routes/_auth/guardians/index'
import { Route as AuthClassroomsIndexRouteImport } from './routes/_auth/classrooms/index'
import { Route as AuthChildrenIndexRouteImport } from './routes/_auth/children/index'
import { Route as AuthBillingIndexRouteImport } from './routes/_auth/billing/index'
import { Route as AuthSchedulingTimeRouteImport } from './routes/_auth/scheduling/time'
import { Route as AuthReportsAuditLogRouteImport } from './routes/_auth/reports/audit-log'
import { Route as AuthRatiosHistoryRouteImport } from './routes/_auth/ratios/history'
import { Route as AuthMessagesIdRouteImport } from './routes/_auth/messages/$id'
import { Route as AuthGuardiansIdRouteImport } from './routes/_auth/guardians/$id'
import { Route as AuthClassroomsIdRouteImport } from './routes/_auth/classrooms/$id'
import { Route as AuthChildrenEnrollRouteImport } from './routes/_auth/children/enroll'
import { Route as AuthChildrenIdRouteImport } from './routes/_auth/children/$id'
import { Route as AuthBillingTemplatesRouteImport } from './routes/_auth/billing/templates'
import { Route as AuthBillingPaymentsRouteImport } from './routes/_auth/billing/payments'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOverviewRoute = AuthOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHelpRoute = AuthHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAttendanceRoute = AuthAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountRoute = AuthAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSubsidiesIndexRoute = AuthSubsidiesIndexRouteImport.update({
  id: '/subsidies/',
  path: '/subsidies/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSchedulingIndexRoute = AuthSchedulingIndexRouteImport.update({
  id: '/scheduling/',
  path: '/scheduling/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsIndexRoute = AuthReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRatiosIndexRoute = AuthRatiosIndexRouteImport.update({
  id: '/ratios/',
  path: '/ratios/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMessagesIndexRoute = AuthMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthImportIndexRoute = AuthImportIndexRouteImport.update({
  id: '/import/',
  path: '/import/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGuardiansIndexRoute = AuthGuardiansIndexRouteImport.update({
  id: '/guardians/',
  path: '/guardians/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClassroomsIndexRoute = AuthClassroomsIndexRouteImport.update({
  id: '/classrooms/',
  path: '/classrooms/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChildrenIndexRoute = AuthChildrenIndexRouteImport.update({
  id: '/children/',
  path: '/children/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBillingIndexRoute = AuthBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSchedulingTimeRoute = AuthSchedulingTimeRouteImport.update({
  id: '/scheduling/time',
  path: '/scheduling/time',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsAuditLogRoute = AuthReportsAuditLogRouteImport.update({
  id: '/reports/audit-log',
  path: '/reports/audit-log',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRatiosHistoryRoute = AuthRatiosHistoryRouteImport.update({
  id: '/ratios/history',
  path: '/ratios/history',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMessagesIdRoute = AuthMessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGuardiansIdRoute = AuthGuardiansIdRouteImport.update({
  id: '/guardians/$id',
  path: '/guardians/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClassroomsIdRoute = AuthClassroomsIdRouteImport.update({
  id: '/classrooms/$id',
  path: '/classrooms/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChildrenEnrollRoute = AuthChildrenEnrollRouteImport.update({
  id: '/children/enroll',
  path: '/children/enroll',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChildrenIdRoute = AuthChildrenIdRouteImport.update({
  id: '/children/$id',
  path: '/children/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBillingTemplatesRoute = AuthBillingTemplatesRouteImport.update({
  id: '/billing/templates',
  path: '/billing/templates',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBillingPaymentsRoute = AuthBillingPaymentsRouteImport.update({
  id: '/billing/payments',
  path: '/billing/payments',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthAccountRoute
  '/attendance': typeof AuthAttendanceRoute
  '/dashboard': typeof AuthDashboardRoute
  '/help': typeof AuthHelpRoute
  '/overview': typeof AuthOverviewRoute
  '/settings': typeof AuthSettingsRoute
  '/pay/$token': typeof PayTokenRoute
  '/billing/payments': typeof AuthBillingPaymentsRoute
  '/billing/templates': typeof AuthBillingTemplatesRoute
  '/children/$id': typeof AuthChildrenIdRoute
  '/children/enroll': typeof AuthChildrenEnrollRoute
  '/classrooms/$id': typeof AuthClassroomsIdRoute
  '/guardians/$id': typeof AuthGuardiansIdRoute
  '/messages/$id': typeof AuthMessagesIdRoute
  '/ratios/history': typeof AuthRatiosHistoryRoute
  '/reports/audit-log': typeof AuthReportsAuditLogRoute
  '/scheduling/time': typeof AuthSchedulingTimeRoute
  '/billing/': typeof AuthBillingIndexRoute
  '/children/': typeof AuthChildrenIndexRoute
  '/classrooms/': typeof AuthClassroomsIndexRoute
  '/guardians/': typeof AuthGuardiansIndexRoute
  '/import/': typeof AuthImportIndexRoute
  '/messages/': typeof AuthMessagesIndexRoute
  '/ratios/': typeof AuthRatiosIndexRoute
  '/reports/': typeof AuthReportsIndexRoute
  '/scheduling/': typeof AuthSchedulingIndexRoute
  '/subsidies/': typeof AuthSubsidiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthAccountRoute
  '/attendance': typeof AuthAttendanceRoute
  '/dashboard': typeof AuthDashboardRoute
  '/help': typeof AuthHelpRoute
  '/overview': typeof AuthOverviewRoute
  '/settings': typeof AuthSettingsRoute
  '/pay/$token': typeof PayTokenRoute
  '/billing/payments': typeof AuthBillingPaymentsRoute
  '/billing/templates': typeof AuthBillingTemplatesRoute
  '/children/$id': typeof AuthChildrenIdRoute
  '/children/enroll': typeof AuthChildrenEnrollRoute
  '/classrooms/$id': typeof AuthClassroomsIdRoute
  '/guardians/$id': typeof AuthGuardiansIdRoute
  '/messages/$id': typeof AuthMessagesIdRoute
  '/ratios/history': typeof AuthRatiosHistoryRoute
  '/reports/audit-log': typeof AuthReportsAuditLogRoute
  '/scheduling/time': typeof AuthSchedulingTimeRoute
  '/billing': typeof AuthBillingIndexRoute
  '/children': typeof AuthChildrenIndexRoute
  '/classrooms': typeof AuthClassroomsIndexRoute
  '/guardians': typeof AuthGuardiansIndexRoute
  '/import': typeof AuthImportIndexRoute
  '/messages': typeof AuthMessagesIndexRoute
  '/ratios': typeof AuthRatiosIndexRoute
  '/reports': typeof AuthReportsIndexRoute
  '/scheduling': typeof AuthSchedulingIndexRoute
  '/subsidies': typeof AuthSubsidiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_auth/account': typeof AuthAccountRoute
  '/_auth/attendance': typeof AuthAttendanceRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/help': typeof AuthHelpRoute
  '/_auth/overview': typeof AuthOverviewRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/pay/$token': typeof PayTokenRoute
  '/_auth/billing/payments': typeof AuthBillingPaymentsRoute
  '/_auth/billing/templates': typeof AuthBillingTemplatesRoute
  '/_auth/children/$id': typeof AuthChildrenIdRoute
  '/_auth/children/enroll': typeof AuthChildrenEnrollRoute
  '/_auth/classrooms/$id': typeof AuthClassroomsIdRoute
  '/_auth/guardians/$id': typeof AuthGuardiansIdRoute
  '/_auth/messages/$id': typeof AuthMessagesIdRoute
  '/_auth/ratios/history': typeof AuthRatiosHistoryRoute
  '/_auth/reports/audit-log': typeof AuthReportsAuditLogRoute
  '/_auth/scheduling/time': typeof AuthSchedulingTimeRoute
  '/_auth/billing/': typeof AuthBillingIndexRoute
  '/_auth/children/': typeof AuthChildrenIndexRoute
  '/_auth/classrooms/': typeof AuthClassroomsIndexRoute
  '/_auth/guardians/': typeof AuthGuardiansIndexRoute
  '/_auth/import/': typeof AuthImportIndexRoute
  '/_auth/messages/': typeof AuthMessagesIndexRoute
  '/_auth/ratios/': typeof AuthRatiosIndexRoute
  '/_auth/reports/': typeof AuthReportsIndexRoute
  '/_auth/scheduling/': typeof AuthSchedulingIndexRoute
  '/_auth/subsidies/': typeof AuthSubsidiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/attendance'
    | '/dashboard'
    | '/help'
    | '/overview'
    | '/settings'
    | '/pay/$token'
    | '/billing/payments'
    | '/billing/templates'
    | '/children/$id'
    | '/children/enroll'
    | '/classrooms/$id'
    | '/guardians/$id'
    | '/messages/$id'
    | '/ratios/history'
    | '/reports/audit-log'
    | '/scheduling/time'
    | '/billing/'
    | '/children/'
    | '/classrooms/'
    | '/guardians/'
    | '/import/'
    | '/messages/'
    | '/ratios/'
    | '/reports/'
    | '/scheduling/'
    | '/subsidies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/attendance'
    | '/dashboard'
    | '/help'
    | '/overview'
    | '/settings'
    | '/pay/$token'
    | '/billing/payments'
    | '/billing/templates'
    | '/children/$id'
    | '/children/enroll'
    | '/classrooms/$id'
    | '/guardians/$id'
    | '/messages/$id'
    | '/ratios/history'
    | '/reports/audit-log'
    | '/scheduling/time'
    | '/billing'
    | '/children'
    | '/classrooms'
    | '/guardians'
    | '/import'
    | '/messages'
    | '/ratios'
    | '/reports'
    | '/scheduling'
    | '/subsidies'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/_auth/account'
    | '/_auth/attendance'
    | '/_auth/dashboard'
    | '/_auth/help'
    | '/_auth/overview'
    | '/_auth/settings'
    | '/pay/$token'
    | '/_auth/billing/payments'
    | '/_auth/billing/templates'
    | '/_auth/children/$id'
    | '/_auth/children/enroll'
    | '/_auth/classrooms/$id'
    | '/_auth/guardians/$id'
    | '/_auth/messages/$id'
    | '/_auth/ratios/history'
    | '/_auth/reports/audit-log'
    | '/_auth/scheduling/time'
    | '/_auth/billing/'
    | '/_auth/children/'
    | '/_auth/classrooms/'
    | '/_auth/guardians/'
    | '/_auth/import/'
    | '/_auth/messages/'
    | '/_auth/ratios/'
    | '/_auth/reports/'
    | '/_auth/scheduling/'
    | '/_auth/subsidies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  PayTokenRoute: typeof PayTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/overview': {
      id: '/_auth/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthOverviewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/help': {
      id: '/_auth/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthHelpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/attendance': {
      id: '/_auth/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthAttendanceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account': {
      id: '/_auth/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthAccountRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/subsidies/': {
      id: '/_auth/subsidies/'
      path: '/subsidies'
      fullPath: '/subsidies/'
      preLoaderRoute: typeof AuthSubsidiesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/scheduling/': {
      id: '/_auth/scheduling/'
      path: '/scheduling'
      fullPath: '/scheduling/'
      preLoaderRoute: typeof AuthSchedulingIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports/': {
      id: '/_auth/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthReportsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ratios/': {
      id: '/_auth/ratios/'
      path: '/ratios'
      fullPath: '/ratios/'
      preLoaderRoute: typeof AuthRatiosIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/messages/': {
      id: '/_auth/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthMessagesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/import/': {
      id: '/_auth/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof AuthImportIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/guardians/': {
      id: '/_auth/guardians/'
      path: '/guardians'
      fullPath: '/guardians/'
      preLoaderRoute: typeof AuthGuardiansIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/classrooms/': {
      id: '/_auth/classrooms/'
      path: '/classrooms'
      fullPath: '/classrooms/'
      preLoaderRoute: typeof AuthClassroomsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/children/': {
      id: '/_auth/children/'
      path: '/children'
      fullPath: '/children/'
      preLoaderRoute: typeof AuthChildrenIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/billing/': {
      id: '/_auth/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthBillingIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/scheduling/time': {
      id: '/_auth/scheduling/time'
      path: '/scheduling/time'
      fullPath: '/scheduling/time'
      preLoaderRoute: typeof AuthSchedulingTimeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports/audit-log': {
      id: '/_auth/reports/audit-log'
      path: '/reports/audit-log'
      fullPath: '/reports/audit-log'
      preLoaderRoute: typeof AuthReportsAuditLogRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ratios/history': {
      id: '/_auth/ratios/history'
      path: '/ratios/history'
      fullPath: '/ratios/history'
      preLoaderRoute: typeof AuthRatiosHistoryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/messages/$id': {
      id: '/_auth/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthMessagesIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/guardians/$id': {
      id: '/_auth/guardians/$id'
      path: '/guardians/$id'
      fullPath: '/guardians/$id'
      preLoaderRoute: typeof AuthGuardiansIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/classrooms/$id': {
      id: '/_auth/classrooms/$id'
      path: '/classrooms/$id'
      fullPath: '/classrooms/$id'
      preLoaderRoute: typeof AuthClassroomsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/children/enroll': {
      id: '/_auth/children/enroll'
      path: '/children/enroll'
      fullPath: '/children/enroll'
      preLoaderRoute: typeof AuthChildrenEnrollRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/children/$id': {
      id: '/_auth/children/$id'
      path: '/children/$id'
      fullPath: '/children/$id'
      preLoaderRoute: typeof AuthChildrenIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/billing/templates': {
      id: '/_auth/billing/templates'
      path: '/billing/templates'
      fullPath: '/billing/templates'
      preLoaderRoute: typeof AuthBillingTemplatesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/billing/payments': {
      id: '/_auth/billing/payments'
      path: '/billing/payments'
      fullPath: '/billing/payments'
      preLoaderRoute: typeof AuthBillingPaymentsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAccountRoute: typeof AuthAccountRoute
  AuthAttendanceRoute: typeof AuthAttendanceRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthHelpRoute: typeof AuthHelpRoute
  AuthOverviewRoute: typeof AuthOverviewRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthBillingPaymentsRoute: typeof AuthBillingPaymentsRoute
  AuthBillingTemplatesRoute: typeof AuthBillingTemplatesRoute
  AuthChildrenIdRoute: typeof AuthChildrenIdRoute
  AuthChildrenEnrollRoute: typeof AuthChildrenEnrollRoute
  AuthClassroomsIdRoute: typeof AuthClassroomsIdRoute
  AuthGuardiansIdRoute: typeof AuthGuardiansIdRoute
  AuthMessagesIdRoute: typeof AuthMessagesIdRoute
  AuthRatiosHistoryRoute: typeof AuthRatiosHistoryRoute
  AuthReportsAuditLogRoute: typeof AuthReportsAuditLogRoute
  AuthSchedulingTimeRoute: typeof AuthSchedulingTimeRoute
  AuthBillingIndexRoute: typeof AuthBillingIndexRoute
  AuthChildrenIndexRoute: typeof AuthChildrenIndexRoute
  AuthClassroomsIndexRoute: typeof AuthClassroomsIndexRoute
  AuthGuardiansIndexRoute: typeof AuthGuardiansIndexRoute
  AuthImportIndexRoute: typeof AuthImportIndexRoute
  AuthMessagesIndexRoute: typeof AuthMessagesIndexRoute
  AuthRatiosIndexRoute: typeof AuthRatiosIndexRoute
  AuthReportsIndexRoute: typeof AuthReportsIndexRoute
  AuthSchedulingIndexRoute: typeof AuthSchedulingIndexRoute
  AuthSubsidiesIndexRoute: typeof AuthSubsidiesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountRoute: AuthAccountRoute,
  AuthAttendanceRoute: AuthAttendanceRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthHelpRoute: AuthHelpRoute,
  AuthOverviewRoute: AuthOverviewRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthBillingPaymentsRoute: AuthBillingPaymentsRoute,
  AuthBillingTemplatesRoute: AuthBillingTemplatesRoute,
  AuthChildrenIdRoute: AuthChildrenIdRoute,
  AuthChildrenEnrollRoute: AuthChildrenEnrollRoute,
  AuthClassroomsIdRoute: AuthClassroomsIdRoute,
  AuthGuardiansIdRoute: AuthGuardiansIdRoute,
  AuthMessagesIdRoute: AuthMessagesIdRoute,
  AuthRatiosHistoryRoute: AuthRatiosHistoryRoute,
  AuthReportsAuditLogRoute: AuthReportsAuditLogRoute,
  AuthSchedulingTimeRoute: AuthSchedulingTimeRoute,
  AuthBillingIndexRoute: AuthBillingIndexRoute,
  AuthChildrenIndexRoute: AuthChildrenIndexRoute,
  AuthClassroomsIndexRoute: AuthClassroomsIndexRoute,
  AuthGuardiansIndexRoute: AuthGuardiansIndexRoute,
  AuthImportIndexRoute: AuthImportIndexRoute,
  AuthMessagesIndexRoute: AuthMessagesIndexRoute,
  AuthRatiosIndexRoute: AuthRatiosIndexRoute,
  AuthReportsIndexRoute: AuthReportsIndexRoute,
  AuthSchedulingIndexRoute: AuthSchedulingIndexRoute,
  AuthSubsidiesIndexRoute: AuthSubsidiesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  PayTokenRoute: PayTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
