import { PUBLIC_BRAND_KNOWLEDGE } from "@pebbledesk/shared/public-knowledge";
import { createFileRoute, Link } from "@tanstack/react-router";
import { BrandMark } from "../components/brand-mark";

export const Route = createFileRoute("/privacy")({
	component: PrivacyPolicyPage,
});

const EFFECTIVE_DATE = "May 28, 2026";
const PRIVACY_EMAIL = PUBLIC_BRAND_KNOWLEDGE.privacyEmail;

export function PrivacyPolicyPage() {
	return (
		<div className="min-h-screen bg-muted/40">
			<div className="mx-auto max-w-3xl px-6 py-12">
				<div className="rounded-xl border border-border bg-background p-8 shadow-sm">
					<BrandMark className="mb-8" wordmarkClassName="text-foreground" />

					<h1 className="text-3xl font-bold text-foreground">Privacy Policy</h1>
					<p className="mt-2 text-sm text-muted-foreground">Effective date: {EFFECTIVE_DATE}</p>
					<p className="mt-1 text-sm text-muted-foreground">
						This policy covers the PebbleDesk childcare-administration platform (the authenticated
						application used by childcare centers). Use of the public PebbleDesk marketing website
						is covered by the privacy notice on that site.
					</p>

					<div className="prose prose-sm mt-8 max-w-none text-foreground prose-headings:text-foreground prose-headings:font-semibold prose-a:text-primary">
						<h2>1. Who we are and our role</h2>
						<p>
							PebbleDesk is a software platform operated by Ventora Labs, a Wyoming corporation
							(&ldquo;PebbleDesk,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;), located at Sheridan,
							Wyoming. PebbleDesk is sold to and used by licensed childcare centers, their owners,
							directors, and staff (each, a &ldquo;Center&rdquo;).
						</p>
						<p>
							For the personal information that a Center enters into or generates within the
							platform &mdash; including information about enrolled children, their parents and
							guardians, and the Center&rsquo;s own staff &mdash; the{" "}
							<strong>Center is the data controller / business</strong> and{" "}
							<strong>
								PebbleDesk acts as the Center&rsquo;s data processor / service provider
							</strong>
							. We process that information only to provide the platform to the Center, under the
							Center&rsquo;s instructions and our customer agreement. We do not sell personal
							information, and we do not use information about children, parents, or staff to build
							advertising profiles or to advertise to those individuals.
						</p>
						<p>
							For a limited set of information &mdash; the account and contact details of the Center
							personnel who register, sign in, are billed, or contact support &mdash; PebbleDesk
							acts as a data controller / business, because we determine how that information is
							used to operate and secure our service.
						</p>

						<h2>2. Whose information is in the platform</h2>
						<p>The platform holds information about three groups of people:</p>
						<ul>
							<li>
								<strong>Children</strong> enrolled at a Center. Children do not create accounts and
								do not interact with PebbleDesk directly. Their information is entered by Center
								staff as part of running the Center.
							</li>
							<li>
								<strong>Parents and guardians</strong> of enrolled children. Guardian records are
								created by Center staff; guardians may receive messages and invoices generated by
								the Center through the platform.
							</li>
							<li>
								<strong>Center staff, directors, and owners</strong>, who hold accounts and operate
								the platform.
							</li>
						</ul>

						<h2>3. What information we collect and process</h2>
						<p>
							<strong>Account and authentication data (staff users).</strong> Name, email address,
							whether the email is verified, an optional profile image URL (supplied by Google when
							a user signs in with Google), a hashed password (for email/password sign-in), Google
							OAuth tokens (when Google sign-in is used), session records including IP address and
							browser user-agent, the Center&rsquo;s role assigned to the user (owner, director, or
							staff), and staff clock-in/clock-out times by classroom.
						</p>
						<p>
							<strong>Children&rsquo;s information (entered by the Center).</strong> First and last
							name, date of birth, age group, enrollment status and dates, classroom assignment,
							attendance check-in/check-out records (including optional signatures captured at
							drop-off/pick-up and free-text notes), subsidy eligibility, and the following{" "}
							<strong>sensitive fields</strong> stored as free text where the Center chooses to
							enter them: allergies, immunization information, and general notes. PebbleDesk does{" "}
							<strong>not</strong> store children&rsquo;s photographs, biometric data, or full
							medical records.
						</p>
						<p>
							<strong>Parent/guardian information (entered by the Center).</strong> First and last
							name, email address, phone number, relationship to the child, authorized-pickup
							designation, and any messages, message replies, and invoices associated with that
							guardian.
						</p>
						<p>
							<strong>Operational, billing, and subsidy data.</strong> Center profile details (name,
							address, phone, license number, licensed capacity, timezone), invoices and line items,
							payment records (method, provider, amounts, provider reference IDs), childcare-subsidy
							case and claim details (program, case number, agency name, authorized hours, rates,
							claim amounts and status), audit reports, and an audit log of actions taken in the
							platform (action type, affected record, the change made, acting user, and IP address).
						</p>
						<p>
							<strong>Diagnostic and product-usage data.</strong> If enabled for the deployment,
							error-monitoring data (via Sentry) and product-analytics events (via PostHog) that
							help us keep the service reliable and understand how the product is used.
						</p>

						<h2>4. How and why we use information, and legal bases</h2>
						<p>We process information to:</p>
						<ul>
							<li>
								provide the platform&rsquo;s core features &mdash; enrollment, attendance and ratio
								tracking, messaging, billing/invoicing, subsidy management, and reporting &mdash; on
								behalf of the Center;
							</li>
							<li>authenticate users, maintain sessions, and secure accounts;</li>
							<li>
								send transactional and account emails (for example invoices and password resets);
							</li>
							<li>
								process payments and, where the Center connects them, sync with accounting tools;
							</li>
							<li>
								maintain audit logs and generate compliance/licensing reports the Center relies on;
							</li>
							<li>monitor, debug, and improve the reliability and usability of the service.</li>
						</ul>
						<p>
							For information where the Center is the controller, our legal basis for processing
							under the GDPR (where applicable) is that we process as a processor on the
							Center&rsquo;s documented instructions; the Center is responsible for its own lawful
							basis and for obtaining any required parental consent for children&rsquo;s
							information. For information where PebbleDesk is the controller (staff account/contact
							and billing data), our bases are performance of our contract with the Center and our
							legitimate interests in operating, securing, and improving the service.
						</p>

						<h2>5. Sub-processors</h2>
						<p>
							We use the following third-party service providers to operate the platform. Each
							processes information only to provide its function to us. This list must be confirmed
							against the live deployment before it is relied upon:
						</p>
						<ul>
							<li>
								<strong>Cloudflare</strong> &mdash; application hosting, serverless compute
								(Workers), and file/asset storage (R2).
							</li>
							<li>
								<strong>Neon</strong> &mdash; managed PostgreSQL database hosting (primary data
								store).
							</li>
							<li>
								<strong>Resend</strong> &mdash; transactional and notification email delivery,
								including inbound message replies.
							</li>
							<li>
								<strong>Stripe</strong> &mdash; subscription billing and, where a Center enables it,
								collection of parent/guardian payments.
							</li>
							<li>
								<strong>Intuit QuickBooks</strong> &mdash; optional accounting synchronization, only
								where a Center connects it.
							</li>
							<li>
								<strong>Google</strong> &mdash; optional sign-in (OAuth) for staff users.
							</li>
							<li>
								<strong>Sentry</strong> &mdash; error and performance monitoring (where enabled).
							</li>
							<li>
								<strong>PostHog</strong> &mdash; product analytics (where enabled).
							</li>
							<li>
								<strong>Ventora Labs shared platform</strong> &mdash; shared infrastructure (such as
								analytics, billing, email rendering, and support tooling) operated by
								PebbleDesk&rsquo;s parent studio.
							</li>
						</ul>

						<h2>6. International transfers</h2>
						<p>
							PebbleDesk and several of its sub-processors are based in or process data in the
							United States. If information is transferred from outside the United States, that
							transfer relies on appropriate safeguards required by applicable law (for example,
							Standard Contractual Clauses).
						</p>

						<h2>7. Retention</h2>
						<p>
							As a processor, we retain information that a Center enters for as long as the Center
							maintains its account, and we delete or return it in accordance with our customer
							agreement after the account ends, subject to short technical backup windows. Centers
							can delete records within the platform; deleting a child or guardian removes their
							associated records. Account and billing information we hold as a controller is
							retained as long as needed to operate the service and meet legal, tax, and accounting
							obligations.
						</p>

						<h2>8. Security</h2>
						<p>
							We take reasonable measures to protect information, including encryption-in-transit
							(HTTPS), authenticated and role-based access scoped to each Center, hashed storage of
							passwords, and audit logging of actions within the platform. We host on established
							cloud infrastructure (Cloudflare and Neon). We describe only the safeguards the
							platform actually implements; we do not currently claim any formal security
							certification (such as SOC 2 or ISO 27001) or independent audit. No method of
							transmission or storage is completely secure.
						</p>

						<h2>9. Your rights</h2>
						<p>
							Depending on where you live, you may have rights to access, correct, delete, or port
							your personal information, or to object to or restrict certain processing, under laws
							such as the EU/UK GDPR and the California Consumer Privacy Act as amended (CCPA/CPRA).
							PebbleDesk does not sell personal information or share it for cross-context behavioral
							advertising.
						</p>
						<p>
							Because PebbleDesk is the Center&rsquo;s service provider for information about
							children, parents/guardians, and staff,{" "}
							<strong>
								requests concerning that information should generally be directed to the Center
							</strong>{" "}
							(the controller), and we will assist the Center in responding. For information
							PebbleDesk holds as a controller (your staff account and billing details), you can
							contact us directly using the details below.
						</p>

						<h2>10. Children&rsquo;s information &mdash; special handling</h2>
						<p>
							Children do not use PebbleDesk and do not provide information to us directly; their
							information is provided by the Center as part of operating its childcare program.
							PebbleDesk is not a child-directed online service and does not knowingly collect
							information directly from children.
						</p>
						<p>
							Where the U.S. Children&rsquo;s Online Privacy Protection Act (COPPA) applies, the
							Center is responsible for providing any required parental notice and obtaining any
							required parental consent; PebbleDesk processes children&rsquo;s information only to
							provide the service to the Center and not for advertising or profiling. Childcare
							records are also typically protected by state childcare-licensing confidentiality
							rules, and may be subject to FERPA only for the limited subset of Centers that qualify
							as education agencies receiving U.S. Department of Education funding. Where children
							in the EU/UK are concerned, the Center is responsible for the lawful basis and any
							consent required under GDPR Article 8.
						</p>

						<h2>11. Cookies and similar technologies</h2>
						<p>
							The platform uses strictly necessary cookies and similar local storage to keep you
							signed in and to operate core features. Where analytics and error monitoring are
							enabled, those tools may set cookies or use similar identifiers for measurement; we do
							not use them for advertising.
						</p>

						<h2>12. Changes to this policy</h2>
						<p>
							We may update this policy as the platform evolves or as legal requirements change.
							When we make material changes, we will update the effective date above and, where
							appropriate, notify Centers.
						</p>

						<h2>13. Contact us</h2>
						<p>
							For privacy questions about the platform, contact us at{" "}
							<a href={`mailto:${PRIVACY_EMAIL}`}>{PRIVACY_EMAIL}</a>, or by mail at Ventora Labs, a
							Wyoming corporation, Sheridan, Wyoming. If you are a parent, guardian, or staff member
							with a request about information held in the platform, please also contact your
							childcare Center, which controls that information.
						</p>
					</div>

					<div className="mt-10 border-t border-border pt-6 text-center text-sm text-muted-foreground">
						<Link to="/login" className="font-medium text-primary hover:underline">
							Back to sign in
						</Link>
					</div>
				</div>
			</div>
		</div>
	);
}
